alias l='ls'
alias ll='ls -lX'
alias ..='cd ..;ls'
alias ...='cd ../../;ls'
alias vim='nvim'
alias v='vim'

alias e='. `pipenv --venv`/bin/activate'
alias wo='workon $(pwd | rev | cut -d '/' -f 1 | rev)'

alias gogogadget_schemamigration='./manage.py schemamigration --auto'

alias pipupgradeall='pip freeze --local | grep -v '^\-e' | cut -d = -f 1  | xargs pip install -U'

alias wow='git status'
alias such='git'
alias very='git'
alias much='./manage.py'
alias many='./manage.py'

alias t='todo.sh'
complete -F _todo t

alias b='redshift -O 6500'
alias r='./manage.py runserver [::]:8000'
alias s='./manage.py shell_plus'
alias mm='./manage.py makemigrations'
alias m='./manage.py migrate'
alias gs='git status'
alias gc='git add -A && git commit -m'
alias gp='git push origin master'
alias grc='git rebase --continue'
alias gra='git rebase --abort'
alias grs='git rebase --skip'
alias garc='git add -A && git rebase --continue'
alias ours='git checkout --ours'
alias theirs='git checkout --theirs'
alias mt='git mergetool'
alias gen='nvim `git diff --name-only | head -1` && git add `git diff --name-only | head -1`'
alias gd='git diff'
