#!/bin/bash

export PYTHONPATH=$PYTHONPATH:$HOME/:$HOME/recursive_root/lib/
export PATH=$PATH:$HOME/scripts/:$HOME/.local/bin:$HOME/recursive_root/scripts/
export SXHKD_SHELL=bash
export PYTHONPYCACHEPREFIX=/tmp

_run() {
    if ! pgrep -x "${1}" &>/dev/null; then
        "$@" &
    fi
}

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width 4
#bspc config bottom_padding 0
#bspc config bottom_padding 0
bspc config window_gap 0
bspc config normal_border_color "#1d2021"
bspc config focused_border_color "#fb4934"

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc config pointer_modifier mod4

#_run panel
_run dunst
#_run picom
_run sxhkd
xset r rate 210 42
